---
output:
  html_document:
    css: custom.css
    includes:
      in_header: favicon.html
editor_options: 
  markdown: 
    wrap: 72
---


# Practical Task: Data Handling Skills

**Aims:**

-   Practice importing a .csv data file into RStudio using `read_csv()`.

-   Practice inspecting your data in RStudio.

-   Use different data wrangling functions to develop your data handling
    skills.

-   Check basic summary statistics.

**Guess Who**\
**Your task:** You have been given a data set containing information
about a group of people. You will use RStudio to inspect, modify, and
filter the data set before investigating a series of clues and identify
mystery people within the data.

## Exercise 1: Import the Data

**Import the Data File `guess_who.csv`**

Before you begin, you will need the tidyverse package loaded.

``` r
install.packages("tidyverse") #install tidyverse if you do not have it.
library(tidyverse) #loads tidyverse.
```

Next import the data file and store it as an object called `dataset`.

``` r
dataset <- read_csv("guess_who.csv")
```

If you see an error saying cannot find function `read_csv()` this
usually means you have not loaded (or installed) the tidyverse package.

## Exercise 2: Inspect and Check Your Data

You've just imported your data file. Before we start playing Guess Who,
let's investigate what information we have about our group of people.

**Take a look at your newly imported data file.**

Check the top right panel (the environment) and also use the code below
to inspect your data set.

``` r
view(dataset) # this will open the data in a new tab.
names(dataset) # this will show the variable names.
```

It is really important to look at the variable names as you'll be using
them in code later on.

Answer the following questions. The drop down will turn **green if
correct** and **red if incorrect.**

::: mcq
<p><strong>Q2.1: **How many variables does this data set have?**</strong></p>

<select class="mcq-select"
  onchange="checkAnswer(this)"> <option value="">Choose an
answer...</option> <option value="wrong">9</option>
<option value="correct">11</option> <option value="wrong">10</option>
<option value="wrong">8</option> </select>
:::

::: mcq
<p><strong>Q2.2: **Which variable would you use to to find out where someone
is from?**</strong></p>

<select class="mcq-select"
  onchange="checkAnswer(this)"> <option value="">Choose an
answer...</option> <option value="correct">city</option>
<option value="wrong">name</option>
<option value="wrong">degree</option> <option value="wrong">id</option>
</select>
:::

## Exercise 3: Change a Variable Name

**One of the variable names is quite long. This can be annoying if we
have to keep typing it out.**

Change the variable name `do_you_own_a_pet` to `pet`. The `rename()`
function will let you rename a variable.

``` r
dataset <- dataset %>%
  rename(pet = do_you_own_a_pet)
```

Check it has worked:

``` r
names(dataset) # ask for the variable names again
```

## Exercise 4: Remove a Variable

**We do not really care about the `age` variable for the next few
exercises.**

Let's remove it.

The code below will create a new object. When making changes to a data set (such as removing columns), it is generally best to keep the original data file called `dataset` unchanged in the environment and save the modified version to a new object.

``` r
mydata <- dataset %>%
  select(-age)
```

This code will:

-   Create a new object called `mydata`.

-   Take our original data called `dataset`.

-   "And then" `%>%`.

-   Use the select() function to remove `age` by placing a minus symbol
    `-` in front of it.

From now on, we will use the object called `mydata` and not the original
data set.

## Exercise 5: Filter Cases

**We can select particular cases in our data set.**

For example, I could ask: how many people were from the city of
Birmingham using the code below:

``` r
mydata %>%
  filter(city == "birmingham") %>%
  count()
```

Check the console (bottom left panel) for the answer.

This code will:

-   Take `mydata` and then...

-   Filter it by the `city` variable.

-   We use a double equals symbol `==` to specify an exact match.

-   I've added "birmingham" in speech marks. Note it is lowercase as to
    match the data set and then...

-   `count()` the number of data points.

**Time to investigate!**\
We now know what information we have about our group. Let's use RStudio
to find our more...

Answer the following questions. The drop down will turn **green if
correct** and **red if incorrect.**

::: mcq
<p><strong>Q5.1: **I'm trying to find someone who studies Law. How many people
in the data set study Law? Adapt the code above to find the
answer.**</strong></p>

<select class="mcq-select"
  onchange="checkAnswer(this)"> <option value="">Choose an
answer...</option> <option value="wrong">10</option>
<option value="correct">9</option> <option value="wrong">8</option>
<option value="wrong">11</option> </select>
:::

::: mcq
<p><strong>Q5.2: **I've changed my mind... I now want to find someone who
studies Psychology. How many people study Psychology?**</strong></p>

<select class="mcq-select"
  onchange="checkAnswer(this)"> <option value="">Choose an
answer...</option> <option value="wrong">8</option>
<option value="wrong">5</option> <option value="correct">6</option>
<option value="wrong">7</option> </select>
:::

## Exercise 6: Guess Who?

**Now let's play Guess Who!**\
We've explored the data set, organised our information, and learned how
to find people who match certain characteristics. It's time to put those
skills to the test.

**We can now filter based on multiple criteria**.

The code below will show us someone who is from Brighton, has a dog, and
does not drink coffee.

``` r
mydata %>%
  filter(city == "brighton", pet == "dog", coffee == 0)
```

We can also use less than/more than symbols to filter data, For example,
this will show all people who have a maths enjoyment score of less than
20:

``` r
mydata %>%
  filter(maths < 20)
```

Use what you have learned above and adapt your code to play Guess Who?
Each of the following questions gives you clues about a person. Use
RStudio to work out who we are looking for!

**Use the clues below to find the name of the mystery person:**\
**Clue 1:** The person is from Cardiff.\
**Clue 2:** They have a hamster.\
**Clue 3:** Their science enjoyment score is less than 10.
 
::: mcq
<p><strong>Q6.1:**Who is this person?**</strong></p>
 
<select class="mcq-select"
onchange="checkAnswer(this)"> <option value="">Choose an
answer...</option> <option value="wrong">Joseph</option>
<option value="wrong">Eleanor</option>
<option value="wrong">Victor</option>
<option value="correct">Natalya</option> </select>
:::

**Question 6.2: Use the clues below to find the name of the next mystery
person:**\
**Clue 1:** The person studies Psychology.\
**Clue 2:** They are from Nottingham.\
**Clue 3:** They do not drink coffee.

::: mcq

<p><strong>Q6.2:Who is this person?</strong></p>

<select class="mcq-select" onchange="checkAnswer(this)">
  <option value="">Choose an answer...</option>
  <option value="wrong">Amelia</option>
  <option value="correct">Taylor</option>
  <option value="wrong">George</option>
  <option value="wrong">Antonio</option>
</select>

:::

## Exercise 7: Create a New Variable

**Sometimes we might want to compute new scores or variables.**

Add up the three enjoyment scores for `maths`, `science`, and `art` to
create an overall score called `total_score`.

``` r
mydata <- mydata %>%
  mutate(total_score = maths + science + art)
```

This code will:

-   Take `mydata` to overwrite it (ready to add the new variable) and
    then...

-   Use the `mutate()` function to create a new variable named
    `total_score` which should equal `=` `maths` `+` `science` `+`
    `art`.

View the data set and look for the new column to see it has worked.

``` r
view(mydata)
```

Now, we can look at who had the highest and lowest total enjoyment
score.

`slice_min` will find the row which has the lowest score:

``` r
mydata %>%
  slice_min(total_score)
```

`slice_max` will find the row which has the highest score:

``` r
mydata %>%
  slice_max(total_score)
```

**Now let's find some more mystery people using just a single clue!**\

::: mcq

<p><strong>Q7.1: **What is the name of the person with the lowest maths enjoyment score?**</strong></p>

<select class="mcq-select" onchange="checkAnswer(this)">
  <option value="">Choose an answer...</option>
  <option value="correct">Jose</option>
  <option value="wrong">Elizabeth</option>
  <option value="wrong">Yan</option>
  <option value="wrong">Olga</option>
</select>

:::

::: mcq

<p><strong>Q7.2: **What is the name of the person with the highest total enjoyment score?**</strong></p>

<select class="mcq-select" onchange="checkAnswer(this)">
  <option value="">Choose an answer...</option>
  <option value="wrong">Natalya</option>
  <option value="wrong">Oliver</option>
  <option value="correct">Yan</option>
  <option value="wrong">Sam</option>
</select>

:::

## Exercise 8: Counting and Removing Missing Data

**Real data sets often are missing data points.**

Different people have differing views on how to treat missing data
points. For today, we will just identify and remove any. If you view the
data, you might notice there are some blanks for `degree` as not
everyone is studying for one.

``` r
sum(is.na(mydata$degree))
```

This code will:

-   Calculate the total number using `sum()` of...

-   Any missing data points (R calls these `is.na`)

-   We can then direct to a particular column using `mydata$degree`.
    This essentially means "look in `mydata` and then the column called
    `degree`". We use the dollar sign `$` to specify the column.

If we want to remove them, we can use `filter()` again!

``` r
mydata <- mydata %>% 
  filter(!is.na(degree))
```

Note: this will overwrite `mydata` and remove the cases.

## Exercise 9: Summary Statistics

**We might want to know what was the average enjoyment score?**

We can use this code to look across the data set as a whole:

``` r
summary(mydata)
```

Look through the output in the console (bottom left panel) and answer
the following questions about this group of people:

::: mcq

<p><strong>Q9.1: What was the mean maths enjoyment score across the data set?</strong></p>

<select class="mcq-select" onchange="checkAnswer(this)">
  <option value="">Choose an answer...</option>
  <option value="correct">30.07</option>
  <option value="wrong">28.52</option>
  <option value="wrong">30.50</option>
  <option value="wrong">25.18</option>
</select>

:::

::: mcq

<p><strong>Q9.2: What is the range for total enjoyment score across the dataset?</strong></p>

<select class="mcq-select" onchange="checkAnswer(this)">
  <option value="">Choose an answer...</option>
  <option value="wrong">100</option>
  <option value="correct">104</option>
  <option value="wrong">125</option>
  <option value="wrong">21</option>
</select>

:::

::: mcq

<p><strong>Q9.3: When you look across the three subjects (maths, science, art), which had the highest mean enjoyment score?</strong></p>

<select class="mcq-select" onchange="checkAnswer(this)">
  <option value="">Choose an answer...</option>
  <option value="wrong">science</option>
  <option value="correct">maths</option>
  <option value="wrong">art</option>
</select>

:::

## Exercise 10: Fixing Broken Code

Help!! My code below is not working. I need your help to fix it...

Fix the code below to work out how many coffees were drunk by the person
from Canterbury and is studying medicine. Try running the code first and
then work out why it doesn't work!

``` r
mydata %>%
  filter(city = "canterburY", degree == medicine)
```

Fix the code below to work out the name of the person who is from
London, has a hamster, studies psychology, and did not drink coffee. Try
running the code first and then work out why it doesn't work!

``` r
mydata =
  filter(city == "London", pet == "hamsta", degree == "psychology", coffee >1)
```

Answer the following questions once you have fixed the code above.

If you get stuck, use the hints below.

::: mcq

<p><strong>Q10.1:**How many coffees were drunk by the person from Canterbury and is studying medicine?**</strong></p>

<select class="mcq-select" onchange="checkAnswer(this)">
  <option value="">Choose an answer...</option>
  <option value="wrong">3</option>
  <option value="wrong">2</option>
  <option value="wrong">1</option>
  <option value="correct">0</option>
</select>

:::

::: mcq

<p><strong>Q10.2**What is the name of the person from London, has a hamster, studies Psychology, and did not drink coffee?**</strong></p>

<select class="mcq-select" onchange="checkAnswer(this)">
  <option value="">Choose an answer...</option>
  <option value="wrong">Sofia</option>
  <option value="correct">Noah</option>
  <option value="wrong">Gemma</option>
  <option value="wrong">Sarah</option>
</select>

:::


------------------------------------------------------------------------

<details>

<summary>👀 Click for a hint</summary>

-   Check for spelling errors: there are two of them.

-   Make sure to use double equals when specifying a label `==`.

-   Use quote marks when necessary. Some are missing.

-   Code is case sensitive. There is a capital letter where there
    shouldn't be one.

-   Use symbols correctly. We want to use the pipe %\>% before we
    filter.

-   Use symbols correctly. More than `>` is not the same as `<`.

</details>

------------------------------------------------------------------------

**Below are three optional GUESS WHO questions requiring you to fix the
code to find the mystery person!**

**Bonus question 1: Fix the code below to find the name of the mystery
person:**\
**Clue 1:** The person is from Manchester.\
**Clue 2:** They study medicine.\
**Clue 3:** They do not enjoy art.

```r
mydata %>%  
  filter(city == "Manchester", degree = "Medicine", art < 10)  
```

::: mcq

<p><strong>Who is this person?</strong></p>

<select class="mcq-select" onchange="checkAnswer(this)">
  <option value="">Choose an answer...</option>
  <option value="wrong">Daniel</option>
  <option value="wrong">Sandra</option>
  <option value="wrong">Anna</option>
  <option value="correct">Victoria</option>
</select>

:::

**Bonus question 2: Fix the code below to see who owns a gecko.**

```r
mydata %>%  
  filter(!pet = "geck0") 
```

::: mcq

<p><strong>Who is this person?</strong></p>

<select class="mcq-select" onchange="checkAnswer(this)">
  <option value="">Choose an answer...</option>
  <option value="correct">Joseph</option>
  <option value="wrong">Oliver</option>
  <option value="wrong">Rosa</option>
  <option value="wrong">Luis</option>
</select>

:::

**Bonus question 3: Fix the code below to see how many students study
law and are from London.**

```r
mydata %>% 
  filter(degree = "law", city == "London"),
  count() 
```

::: mcq

<p><strong>How many people?</strong></p>

<select class="mcq-select" onchange="checkAnswer(this)">
  <option value="">Choose an answer...</option>
  <option value="wrong">0</option>
  <option value="wrong">1</option>
  <option value="correct">2</option>
  <option value="wrong">3</option>
</select>

:::

------------------------------------------------------------------------

**Well Done. You have reached the end of the workshop.**

------------------------------------------------------------------------

```{=html}
<script>
document.addEventListener("DOMContentLoaded", function () {

  const copyIcon = `
    <svg width="16" height="16" viewBox="0 0 24 24"
         fill="none" stroke="currentColor" stroke-width="2"
         stroke-linecap="round" stroke-linejoin="round">
      <rect x="9" y="9" width="13" height="13" rx="2"></rect>
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
    </svg>`;

  const checkIcon = `
    <svg width="16" height="16" viewBox="0 0 24 24"
         fill="none" stroke="currentColor" stroke-width="2"
         stroke-linecap="round" stroke-linejoin="round">
      <polyline points="20 6 9 17 4 12"></polyline>
    </svg>`;

  document.querySelectorAll("pre code").forEach(function (codeBlock) {

    const pre = codeBlock.parentElement;

    const button = document.createElement("button");
    button.className = "copy-code-button";
    button.type = "button";
    button.innerHTML = copyIcon;
    button.title = "Copy code";
    button.setAttribute("aria-label", "Copy code");

    button.addEventListener("click", async function () {

      await navigator.clipboard.writeText(codeBlock.innerText);

      button.innerHTML = checkIcon;
      button.title = "Copied";

      setTimeout(function () {
        button.innerHTML = copyIcon;
        button.title = "Copy code";
      }, 1500);

    });

    pre.style.position = "relative";
    pre.appendChild(button);

  });

});
</script>
```

```{=html}
<script>
function checkAnswer(answer) {

  if (answer.value === "correct") {
    answer.style.backgroundColor = "#DDF3E4";
    answer.style.color = "#185C37";
    answer.style.borderColor = "#2E8B57";
  }

  else if (answer.value === "wrong") {
    answer.style.backgroundColor = "#F8DDDF";
    answer.style.color = "#8F3030";
    answer.style.borderColor = "#C94C4C";
  }

  else {
    answer.style.backgroundColor = "#FFFFFF";
    answer.style.color = "#07181B";
    answer.style.borderColor = "#D6E2E5";
  }

}
</script>
```
